apiVersion: v1
kind: Pod
metadata:
  name: shared-volume-pod

spec:
  volumes:
    - name: shared-data
      emptyDir: {}

  containers:
    - name: web-server
      image: nginx
      volumeMounts:
        - name: shared-data
          mountPath: /usr/share/nginx/html

    - name: data-updater
      image: debian
      command: ["/bin/sh", "-c"]
      args:
        - |
          while true; do
            date >> /shared/index.html;
            sleep 1;
          done
      volumeMounts:
        - name: shared-data
          mountPath: /shared