apiVersion: v1
kind: Pod
metadata:
  name: targeted-pod
spec:
  nodeSelector:
    env: prod

  tolerations:
    - key: "env"
      operator: "Equal"
      value: "prod"
      effect: "NoSchedule"

  containers:
    - name: nginx
      image: nginx